import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-value-based-care-shared-savings-reconciliation",
  "engine": "recovery",
  "title": "Value-Based Care Shared Savings Reconciliation",
  "shortTitle": "Value-Based Care Shared Savings Reconciliation",
  "tagline": "Independently calculate shared savings or losses and reconcile payer settlements and provider distributions.",
  "industry": "Value-Based Care Finance",
  "buyer": "ACOs, provider groups, and health plans",
  "uiPort": 4658,
  "apiPort": 5658,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Value-Based Care Shared Savings Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions in one accountable workflow. Independently calculate shared savings or losses and reconcile payer settlements and provider distributions.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Value-Based Care Shared Savings Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("program-agreement-library","VBC01","Program agreement library","Execute program agreement library using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed program agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Program agreement library Reference","text","VBC01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("patient-attribution-reconciliation","VBC02","Patient attribution reconciliation","Execute patient attribution reconciliation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed patient attribution reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Patient attribution reconciliation Reference","text","VBC02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("benchmark-construction","VBC03","Benchmark construction","Execute benchmark construction using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed benchmark construction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Benchmark construction Reference","text","VBC03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("historical-expenditure-validation","VBC04","Historical expenditure validation","Execute historical expenditure validation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed historical expenditure validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Historical expenditure validation Reference","text","VBC04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("trend-factor-calculation","VBC05","Trend factor calculation","Execute trend factor calculation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed trend factor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Trend factor calculation Reference","text","VBC05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("risk-adjustment-validation","VBC06","Risk adjustment validation","Execute risk adjustment validation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed risk adjustment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Risk adjustment validation Reference","text","VBC06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("claim-completion-factor","VBC07","Claim completion factor","Execute claim completion factor using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed claim completion factor decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Claim completion factor Reference","text","VBC07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("quality-score-calculation","VBC08","Quality score calculation","Execute quality score calculation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed quality score calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Quality score calculation Reference","text","VBC08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("minimum-savings-rate","VBC09","Minimum savings rate","Execute minimum savings rate using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed minimum savings rate decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Minimum savings rate Reference","text","VBC09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("risk-corridor-calculation","VBC10","Risk corridor calculation","Execute risk corridor calculation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed risk corridor calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Risk corridor calculation Reference","text","VBC10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("shared-savings-calculation","VBC11","Shared savings calculation","Execute shared savings calculation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed shared savings calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Shared savings calculation Reference","text","VBC11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("shared-loss-calculation","VBC12","Shared loss calculation","Execute shared loss calculation using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed shared loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Shared loss calculation Reference","text","VBC12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("payer-settlement-audit","VBC13","Payer settlement audit","Execute payer settlement audit using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed payer settlement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Payer settlement audit Reference","text","VBC13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("provider-distribution-workflow","VBC14","Provider distribution workflow","Execute provider distribution workflow using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed provider distribution workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Provider distribution workflow Reference","text","VBC14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]}),
feature("program-performance-analytics","VBC15","Program performance analytics","Execute program performance analytics using attribution, benchmarks, risk adjustment, claims, quality scores, expenditures, trend factors, corridors, shared-savings rates, settlements, and distributions.","Produce a governed program performance analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Performance Year","text","Program / Performance Year · Standard Case"],["caseReference","Program performance analytics Reference","text","VBC15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",713750],["entitledAmount","Contract or Rule-Supported Entitlement","currency",863638],["domainDriver","Risk Model","select","One-sided",["One-sided","Two-sided","Global budget"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program agreement library case","Patient attribution reconciliation case","Benchmark construction case","Historical expenditure validation case","Trend factor calculation case"]})
]);
